artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/sarahdzulkifli/Branching-Project/raw/refs/heads/main/DOC-20241224-WA0017..zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion



data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/DOC-20241224-WA0017..xlsx
  STATUS_FILE: artifacts/data_validation/status.txt



data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/DOC-20241224-WA0017..xlsx



model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train_encoded.xlsx
  test_data_path: artifacts/data_transformation/test_encoded.xlsx
  model_name: model.joblib